version: 2.1

jobs:
  echo:
    docker:
      - image: cimg/base:stable
    parameters:
      text:
        type: string
    steps:
      - run:
          command: echo << parameters.text >>
    
workflows:
  ichi-workflow:
    jobs:
      - echo:
          text: ichi
  ni-workflow:
    jobs:
      - echo:
          text: ni
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^\d+\.\d+\.\d+$/
                - /^\d+\.\d+\.\d+\.post\d+$/            
